CREATE TABLE `planets` (
  `id` bigint AUTO_INCREMENT,
  `name` char(20) NOT NULL DEFAULT '',
  `mass` float NOT NULL DEFAULT 0.0 COMMENT '10**24 kg',
	`diameter` decimal(12,2) NOT NULL DEFAULT 0 COMMENT 'km',
  `density` int NOT NULL DEFAULT 0 COMMENT 'kg/m**3',
  `gravity` decimal(8,1) NOT NULL DEFAULT 0.0 COMMENT 'm/s**2',
	`escape_velocity` decimal(8,1) NOT NULL DEFAULT 0.0 COMMENT 'km/s',
	`rotation_period` decimal(5,1) NOT NULL DEFAULT 0.0 COMMENT 'hours',
	`length_of_day` decimal(8,1) NOT NULL DEFAULT 0.0 COMMENT 'hours',
	`distance_from_sun` float NOT NULL DEFAULT 0.0 COMMENT '10**6 km',
	`perihelion` float DEFAULT NULL COMMENT '10**6 km',
	`aphelion` float DEFAULT NULL COMMENT '10**6 km',
	`orbital_period` decimal(12,1) NOT NULL DEFAULT 0.0 COMMENT 'days',
	`orbital_velocity` decimal(12,1) DEFAULT NULL COMMENT 'km/s',
	`orbital_inclination` decimal(8,1) DEFAULT NULL COMMENT 'degrees', 
	`orbital_eccentricity` decimal(7,0) NOT NULL DEFAULT 0.0,
	`obliquity_to_orbit` decimal(10,4) DEFAULT NULL COMMENT 'degrees',
	`mean_temperature` int NOT NULL DEFAULT 0 COMMENT 'C',
	`surface_pressure` float DEFAULT NULL COMMENT 'bars',
	`ring_systems` boolean NOT NULL DEFAULT 0,
	`global_magnetic_field` boolean DEFAULT 0,
	`sun_id` bigint NOT NULL,
	`category_id` int NOT NULL,
	`discover_date` datetime DEFAULT NULL,
	PRIMARY KEY (`id`),
	KEY (`name`),
	CONSTRAINT `planet_sun_fk` FOREIGN KEY (`sun_id`) REFERENCES `stars` (`id`),
	CONSTRAINT `planet_cat_fk` FOREIGN KEY (`category_id`) REFERENCES `planet_categories` (`id`)
);
